-- 985Fitness schema v1.6
-- MySQL 8.x / InnoDB / utf8mb4
-- Primary keys are generated by the application with a Snowflake-style ID.
-- Create and select the database before running this Flyway migration.

SET NAMES utf8mb4;

CREATE TABLE t_985fitness_user (
    id              BIGINT       NOT NULL COMMENT '雪花ID',
    openid          VARCHAR(64)  NOT NULL COMMENT '微信openid（小程序用户唯一标识）',
    unionid         VARCHAR(64)      NULL COMMENT '微信unionid（多平台打通用）',
    nickname        VARCHAR(60)      NULL COMMENT '微信昵称',
    avatar          VARCHAR(500)     NULL COMMENT '头像URL',
    phone           VARCHAR(20)      NULL COMMENT '手机号（加密存储）',
    gender          TINYINT          NULL COMMENT '性别：0未知 1男 2女',
    birthday        DATE             NULL COMMENT '生日',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1正常 0冻结 2注销',
    remark          VARCHAR(500)     NULL COMMENT '后台备注',
    register_time   DATETIME     NOT NULL COMMENT '注册时间',
    last_login_time DATETIME         NULL COMMENT '最后登录时间',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_openid (openid),
    KEY idx_user_phone (phone),
    KEY idx_user_register_time (register_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表（微信小程序会员）';

CREATE TABLE t_985fitness_admin (
    id              BIGINT       NOT NULL,
    username        VARCHAR(50)  NOT NULL COMMENT '登录账号',
    password        VARCHAR(255) NOT NULL COMMENT 'BCrypt密码摘要',
    real_name       VARCHAR(50)      NULL COMMENT '真实姓名',
    phone           VARCHAR(20)      NULL COMMENT '手机号',
    avatar          VARCHAR(500)     NULL COMMENT '头像URL',
    role            TINYINT      NOT NULL COMMENT '角色：1超级管理员 2店长 3运营 4财务',
    store_id        BIGINT           NULL COMMENT '管辖门店ID，NULL表示全部门店',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
    last_login_ip   VARCHAR(64)      NULL COMMENT '最后登录IP',
    last_login_time DATETIME         NULL COMMENT '最后登录时间',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
    PRIMARY KEY (id),
    UNIQUE KEY uk_admin_username (username),
    KEY idx_admin_store (store_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='管理后台管理员表';

CREATE TABLE t_985fitness_store (
    id              BIGINT        NOT NULL,
    name            VARCHAR(100)  NOT NULL COMMENT '门店名称',
    short_name      VARCHAR(50)       NULL COMMENT '门店简称',
    address         VARCHAR(200)      NULL COMMENT '详细地址',
    longitude       DECIMAL(10, 6)    NULL COMMENT '经度（高德坐标系）',
    latitude        DECIMAL(10, 6)    NULL COMMENT '纬度（高德坐标系）',
    phone           VARCHAR(20)       NULL COMMENT '门店电话',
    service_phone   VARCHAR(20)       NULL COMMENT '客服电话',
    wifi_name       VARCHAR(50)       NULL COMMENT 'WIFI SSID',
    wifi_password   VARCHAR(50)       NULL COMMENT 'WIFI密码',
    cover           JSON              NULL COMMENT '首页图片信息',
    intro           TEXT              NULL COMMENT '门店介绍',
    photos          JSON              NULL COMMENT '到店指引照片数组',
    sort_order      INT           NOT NULL DEFAULT 0 COMMENT '排序权重',
    create_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT       NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='门店表';

CREATE TABLE t_985fitness_coach (
    id              BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL COMMENT '关联用户ID',
    store_id        BIGINT       NOT NULL COMMENT '归属门店ID',
    name            VARCHAR(50)  NOT NULL COMMENT '真实姓名',
    avatar          VARCHAR(500)     NULL COMMENT '头像URL',
    gender          TINYINT          NULL COMMENT '性别：0未知 1男 2女',
    phone           VARCHAR(20)      NULL COMMENT '手机号',
    specialties     JSON             NULL COMMENT '专长标签数组',
    intro           TEXT             NULL COMMENT '个人简介',
    price           BIGINT       NOT NULL DEFAULT 0 COMMENT '课时费，单位分',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1可预约 0休息 2离职',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
    PRIMARY KEY (id),
    UNIQUE KEY uk_coach_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教练和助教表';

CREATE TABLE t_985fitness_schedule (
    id              BIGINT    NOT NULL,
    store_id        BIGINT    NOT NULL COMMENT '门店ID',
    coach_id        BIGINT    NOT NULL COMMENT '教练或助教ID',
    start_time      DATETIME  NOT NULL COMMENT '开始时间',
    end_time        DATETIME  NOT NULL COMMENT '结束时间',
    capacity        INT       NOT NULL DEFAULT 0 COMMENT '人数上限',
    booked_count    INT       NOT NULL DEFAULT 0 COMMENT '已预约人数',
    status          TINYINT   NOT NULL DEFAULT 1 COMMENT '状态：1可预约 0已满',
    create_time     DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT   NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
    PRIMARY KEY (id),
    KEY idx_schedule_coach_time (coach_id, start_time),
    KEY idx_schedule_store_time (store_id, start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教练排班时段表';

CREATE TABLE t_985fitness_booking (
    id              BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL COMMENT '用户ID',
    schedule_id     BIGINT       NOT NULL COMMENT '排班ID',
    order_id        BIGINT           NULL COMMENT '关联订单ID',
    coach_id        BIGINT           NULL COMMENT '教练或助教ID',
    payment_method  VARCHAR(20)      NULL COMMENT '支付方式：WECHAT/STORED_VALUE/COUPON',
    amount          BIGINT       NOT NULL DEFAULT 0 COMMENT '实付金额，单位分',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1待上课 2已签到 3已取消 4已退款',
    is_verify       TINYINT      NOT NULL DEFAULT 1 COMMENT '教练是否确认：1确认 0取消',
    checkin_time    DATETIME         NULL COMMENT '签到时间',
    cancel_time     DATETIME         NULL COMMENT '取消时间',
    cancel_reason   VARCHAR(200)     NULL COMMENT '取消原因',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_booking_user_schedule (user_id, schedule_id),
    KEY idx_booking_user (user_id),
    KEY idx_booking_schedule (schedule_id),
    KEY idx_booking_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='预约表';

CREATE TABLE t_985fitness_order (
    id              BIGINT       NOT NULL,
    order_no        VARCHAR(32)  NOT NULL COMMENT '业务订单号',
    user_id         BIGINT       NOT NULL COMMENT '用户ID',
    biz_type        TINYINT      NOT NULL COMMENT '业务类型：1课程预约 2买卡 3储值充值',
    biz_id          BIGINT           NULL COMMENT '业务ID',
    total_amount    BIGINT       NOT NULL DEFAULT 0 COMMENT '总金额，单位分',
    pay_amount      BIGINT       NOT NULL DEFAULT 0 COMMENT '实付金额，单位分',
    payment_method  VARCHAR(20)      NULL COMMENT '支付方式：WECHAT/ALIPAY/STORED_VALUE',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1待支付 2已支付 3已取消 4已退款',
    prepay_id       VARCHAR(64)      NULL COMMENT '微信预支付ID',
    transaction_id  VARCHAR(64)      NULL COMMENT '支付渠道交易号',
    paid_at         DATETIME         NULL COMMENT '支付时间',
    refunded_at     DATETIME         NULL COMMENT '退款时间',
    refund_amount   BIGINT       NOT NULL DEFAULT 0 COMMENT '已退款金额，单位分',
    expired_at      DATETIME         NULL COMMENT '支付过期时间',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_no (order_no),
    KEY idx_order_user (user_id),
    KEY idx_order_biz (biz_type, biz_id),
    KEY idx_order_status (status),
    KEY idx_order_paid_at (paid_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务订单表';

CREATE TABLE t_985fitness_payment (
    id              BIGINT       NOT NULL,
    order_id        BIGINT       NOT NULL COMMENT '订单ID',
    user_id         BIGINT       NOT NULL COMMENT '用户ID',
    channel         VARCHAR(20)  NOT NULL COMMENT '渠道：WECHAT_PAY/STORED_VALUE',
    transaction_id  VARCHAR(64)      NULL COMMENT '支付渠道交易号',
    amount          BIGINT       NOT NULL COMMENT '支付金额，单位分',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1待支付 2成功 3失败 4已退款',
    raw_response    JSON             NULL COMMENT '支付回调原始报文',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_payment_order (order_id),
    KEY idx_payment_transaction (transaction_id),
    KEY idx_payment_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付流水表';

CREATE TABLE t_985fitness_refund_record (
    id              BIGINT       NOT NULL,
    refund_no       VARCHAR(32)  NOT NULL COMMENT '退款单号',
    order_id        BIGINT       NOT NULL COMMENT '原订单ID',
    user_id         BIGINT       NOT NULL COMMENT '用户ID',
    amount          BIGINT       NOT NULL COMMENT '退款金额，单位分',
    reason          VARCHAR(200)     NULL COMMENT '退款原因',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1待退款 2成功 3失败',
    refund_id       VARCHAR(64)      NULL COMMENT '渠道退款单号',
    fail_reason     VARCHAR(500)     NULL COMMENT '失败原因',
    operator        BIGINT           NULL COMMENT '操作管理员ID',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_refund_no (refund_no),
    KEY idx_refund_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退款记录表';

CREATE TABLE t_985fitness_card_product (
    id              BIGINT       NOT NULL,
    name            VARCHAR(100) NOT NULL COMMENT '会员卡名称',
    type            TINYINT      NOT NULL COMMENT '类型：1次卡 2月卡 3季卡 4年卡 5学期卡 6体验卡',
    valid_days      INT          NOT NULL COMMENT '有效天数',
    price           BIGINT       NOT NULL COMMENT '售价，单位分',
    description     VARCHAR(500)     NULL COMMENT '卖点描述',
    sort_order      INT          NOT NULL DEFAULT 0 COMMENT '排序权重',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1上架 0下架',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
    PRIMARY KEY (id),
    KEY idx_card_product_type (type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会员卡商品表';

CREATE TABLE t_985fitness_user_card (
    id              BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL COMMENT '用户ID',
    card_product_id BIGINT       NOT NULL COMMENT '会员卡商品ID',
    order_id        BIGINT       NOT NULL COMMENT '购买订单ID',
    remain_times    INT          NOT NULL DEFAULT 0 COMMENT '剩余天数',
    start_time      DATETIME         NULL COMMENT '生效时间',
    expire_time     DATETIME     NOT NULL COMMENT '到期时间',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1使用中 2已过期 3已退款',
    frozen          TINYINT      NOT NULL DEFAULT 0 COMMENT '是否冻结：0否 1是',
    is_agree        TINYINT      NOT NULL DEFAULT 1 COMMENT '是否同意会员卡协议：0否 1是',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_user_card_user (user_id),
    KEY idx_user_card_expire (expire_time),
    KEY idx_user_card_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户会员卡表';

CREATE TABLE t_985fitness_stored_value_account (
    id              BIGINT    NOT NULL,
    user_id         BIGINT    NOT NULL COMMENT '用户ID',
    balance         BIGINT    NOT NULL DEFAULT 0 COMMENT '实付余额，单位分',
    gift_balance    BIGINT    NOT NULL DEFAULT 0 COMMENT '赠送余额，单位分',
    frozen          BIGINT    NOT NULL DEFAULT 0 COMMENT '冻结金额，单位分',
    total_recharge  BIGINT    NOT NULL DEFAULT 0 COMMENT '累计充值，单位分',
    total_consume   BIGINT    NOT NULL DEFAULT 0 COMMENT '累计消费，单位分',
    create_time     DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_stored_value_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='储值账户表';

CREATE TABLE t_985fitness_stored_value_transaction (
    id              BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL COMMENT '用户ID',
    biz_type        TINYINT      NOT NULL COMMENT '类型：1充值 2消费 3退款 4赠送 5过期 6冻结 7解冻',
    scene           VARCHAR(16)      NULL COMMENT '场景：CARD/COURSE/ADDON/RECHARGE',
    direction       TINYINT      NOT NULL COMMENT '方向：1入账 2出账',
    amount          BIGINT       NOT NULL COMMENT '变动金额，单位分',
    balance_after   BIGINT       NOT NULL COMMENT '变动后余额，单位分',
    ref_order_id    BIGINT           NULL COMMENT '关联订单ID',
    ref_biz_id      VARCHAR(64)      NULL COMMENT '业务幂等键',
    remark          VARCHAR(200)     NULL COMMENT '备注',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_stored_value_user_time (user_id, create_time),
    KEY idx_stored_value_scene (scene),
    KEY idx_stored_value_ref_biz (ref_biz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='储值流水表（只增不改）';

CREATE TABLE t_985fitness_coach_income_account (
    id              BIGINT    NOT NULL,
    coach_id        BIGINT    NOT NULL COMMENT '教练或助教ID',
    balance         BIGINT    NOT NULL DEFAULT 0 COMMENT '可结算余额，单位分',
    total_income    BIGINT    NOT NULL DEFAULT 0 COMMENT '累计收入，单位分',
    total_paid      BIGINT    NOT NULL DEFAULT 0 COMMENT '累计已结算，单位分',
    version         INT       NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    create_time     DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_income_account_coach (coach_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教练收入账户表';

CREATE TABLE t_985fitness_coach_income_log (
    id              BIGINT       NOT NULL,
    coach_id        BIGINT       NOT NULL COMMENT '教练或助教ID',
    biz_type        TINYINT      NOT NULL COMMENT '类型：1入账 2退款扣回 3打款 4管理员调整',
    direction       TINYINT      NOT NULL COMMENT '方向：1增加 2减少',
    amount          BIGINT       NOT NULL COMMENT '金额，单位分',
    balance_after   BIGINT       NOT NULL COMMENT '变动后余额，单位分',
    ref_order_id    BIGINT           NULL COMMENT '关联订单ID',
    ref_biz_id      VARCHAR(64)      NULL COMMENT '业务幂等键',
    remark          VARCHAR(200)     NULL COMMENT '备注',
    operator        BIGINT           NULL COMMENT '操作管理员ID',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_coach_income_time (coach_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教练收入流水表（只增不改）';

CREATE TABLE t_985fitness_contract_template (
    id              BIGINT       NOT NULL,
    code            VARCHAR(32)  NOT NULL COMMENT '合同编码',
    title           VARCHAR(100) NOT NULL COMMENT '合同标题',
    content         MEDIUMTEXT   NOT NULL COMMENT '合同全文（Markdown或HTML）',
    version         VARCHAR(20)  NOT NULL COMMENT '合同版本号',
    effective_date  DATE         NOT NULL COMMENT '生效日期',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_contract_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同模板版本表';

CREATE TABLE t_985fitness_contract_signature (
    id                  BIGINT       NOT NULL,
    user_id             BIGINT       NOT NULL COMMENT '用户ID',
    contract_id         BIGINT       NOT NULL COMMENT '合同模板版本ID',
    contract_version    VARCHAR(20)  NOT NULL COMMENT '签署时合同版本号',
    signed_at           DATETIME     NOT NULL COMMENT '签署时间',
    signed_ip           VARCHAR(64)      NULL COMMENT '签署IP',
    signed_ua           VARCHAR(500)     NULL COMMENT '签署设备UA',
    signature_hash      VARCHAR(64)  NOT NULL COMMENT 'SHA-256存证摘要',
    signature_method    TINYINT      NOT NULL DEFAULT 1 COMMENT '方式：1电子勾选 2电子签名 3手写',
    is_revoked          TINYINT      NOT NULL DEFAULT 0 COMMENT '是否撤销：0否 1是',
    revoked_at          DATETIME         NULL COMMENT '撤销时间',
    create_time         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_contract_signature_hash (signature_hash),
    UNIQUE KEY uk_contract_signature_user_version (user_id, contract_id, contract_version),
    KEY idx_contract_signature_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同签署记录表';

CREATE TABLE t_985fitness_user_face (
    id              BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL COMMENT '用户ID',
    face_id         VARCHAR(64)         NULL COMMENT '设备或服务商人脸ID',
    vendor          VARCHAR(32)         NULL COMMENT '服务商：WECHAT/HAIKANG/SENSETIME',
    feature_enc     VARBINARY(2000)     NULL COMMENT '加密后人脸特征值',
    image_url       VARCHAR(500)        NULL COMMENT '加密对象存储中的原图地址',
    status          TINYINT         NOT NULL DEFAULT 1 COMMENT '状态：1有效 0删除',
    expire_time     DATETIME            NULL COMMENT '过期时间',
    create_time     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_face_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户人脸档案表';

CREATE TABLE t_985fitness_access_log (
    id              BIGINT       NOT NULL,
    user_id         BIGINT           NULL COMMENT '用户ID，识别失败时为NULL',
    device_code     VARCHAR(64)  NOT NULL COMMENT '设备编号',
    direction       TINYINT      NOT NULL COMMENT '方向：1进 2出',
    verify_type     VARCHAR(16)  NOT NULL COMMENT '方式：FACE/QRCODE/CARD',
    verify_result   TINYINT      NOT NULL COMMENT '结果：1成功 0失败',
    fail_reason     VARCHAR(100)     NULL COMMENT '失败原因',
    access_time     DATETIME     NOT NULL COMMENT '通行时间',
    raw_data        JSON             NULL COMMENT '设备原始报文',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_access_user_time (user_id, access_time),
    KEY idx_access_device_time (device_code, access_time),
    KEY idx_access_time (access_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='门禁通行记录表';

CREATE TABLE t_985fitness_equipment_repair (
    id              BIGINT       NOT NULL,
    equipment_id    BIGINT       NOT NULL COMMENT '器械ID',
    store_id        BIGINT       NOT NULL COMMENT '门店ID',
    user_id         BIGINT           NULL COMMENT '报修用户ID',
    description     TEXT         NOT NULL COMMENT '故障描述',
    images          JSON             NULL COMMENT '图片URL数组，最多3张',
    status          TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1待处理 2处理中 3已完成 4已取消',
    handler_id      BIGINT           NULL COMMENT '处理人ID',
    handle_note     TEXT             NULL COMMENT '处理备注',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_repair_equipment (equipment_id),
    KEY idx_repair_store_status (store_id, status),
    KEY idx_repair_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='器械报修工单表';

CREATE TABLE t_985fitness_announcement (
    id              BIGINT       NOT NULL,
    store_id        BIGINT       NOT NULL COMMENT '门店ID',
    title           VARCHAR(100) NOT NULL COMMENT '公告标题',
    summary         VARCHAR(200)     NULL COMMENT '摘要',
    content         MEDIUMTEXT       NULL COMMENT '公告全文',
    images          JSON             NULL COMMENT '图片数组',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='门店公告表';

CREATE TABLE t_985fitness_assistant_application (
    id                  BIGINT       NOT NULL,
    user_id             BIGINT       NOT NULL COMMENT '申请用户ID',
    intro               TEXT             NULL COMMENT '个人简介',
    specialties         JSON             NULL COMMENT '专长标签数组',
    available_time      JSON             NULL COMMENT '可预约时间说明',
    images              JSON             NULL COMMENT '运动照片数组',
    videos              JSON             NULL COMMENT '运动视频数组',
    status              TINYINT       NOT NULL DEFAULT 1 COMMENT '状态：1待审 2通过 3拒绝',
    reject_reason       VARCHAR(200)      NULL COMMENT '拒绝原因',
    review_by           BIGINT            NULL COMMENT '审核管理员ID',
    review_time         DATETIME          NULL COMMENT '审核时间',
    last_apply_time     DATETIME      NOT NULL COMMENT '最近申请时间',
    create_time         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_assistant_application_user (user_id),
    KEY idx_assistant_application_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='助教申请表';

CREATE TABLE t_985fitness_external_coupon (
    id              BIGINT       NOT NULL,
    platform        VARCHAR(16)  NOT NULL COMMENT '平台：DOUYIN/MEITUAN',
    code            VARCHAR(64)  NOT NULL COMMENT '平台券码',
    sku_id          VARCHAR(64)      NULL COMMENT '平台商品ID',
    sku_name        VARCHAR(200)     NULL COMMENT '商品名称快照',
    face_value      BIGINT           NULL COMMENT '面值，单位分',
    user_phone      VARCHAR(20)      NULL COMMENT '购券手机号',
    verify_status   TINYINT      NOT NULL DEFAULT 1 COMMENT '状态：1待核销 2已核销 3已退券',
    verify_time     DATETIME         NULL COMMENT '核销时间',
    verify_by       BIGINT           NULL COMMENT '核销员工ID',
    store_id        BIGINT           NULL COMMENT '核销门店ID',
    raw_response    JSON             NULL COMMENT '平台原始响应',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_external_coupon_platform_code (platform, code),
    KEY idx_external_coupon_platform_status (platform, verify_status),
    KEY idx_external_coupon_store_time (store_id, verify_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='抖音和美团券核销记录表';

CREATE TABLE t_985fitness_product (
    id              BIGINT       NOT NULL,
    name            VARCHAR(100) NOT NULL COMMENT '商品名称',
    category        VARCHAR(50)  NOT NULL COMMENT '商品分类',
    price           BIGINT       NOT NULL COMMENT '售价，单位分',
    stock           INT          NOT NULL DEFAULT 0 COMMENT '库存',
    image_url       VARCHAR(500)     NULL COMMENT '商品图片URL',
    status          TINYINT      NOT NULL DEFAULT 0 COMMENT '状态：1上架 0下架',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品销售预留表';
